version: '2'
services:
  inosc-app:
    image: inosc
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://inosc-postgresql:5432/inosc
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  inosc-postgresql:
    extends:
      file: postgresql.yml
      service: inosc-postgresql
